datadocs:
    index_name: search_datadocs_v1
    type_name: datadocs
    mappings: # Keep this same in mappings
        settings:
            analysis:
                analyzer:
                    user_content_analyzer:
                        type: custom
                        tokenizer: standard
                        char_filter:
                            - html_strip
                        filter:
                            - lowercase
        mappings:
            properties:
                id:
                    type: long
                environment_id:
                    type: long
                owner_uid:
                    type: long
                title:
                    type: text
                    analyzer: snowball
                cells:
                    type: text
                    analyzer: user_content_analyzer
                created_at:
                    type: long
                public:
                    type: boolean
                readable_user_ids:
                    type: integer
tables:
    index_name: search_tables_v1
    type_name: tables # Keep this same in mappings
    mappings:
        settings:
            analysis:
                analyzer:
                    user_content_analyzer:
                        type: custom
                        tokenizer: standard
                        char_filter:
                            - html_strip
                    table_name_lowercase:
                        type: custom
                        tokenizer: alphanum_tokenizer
                        filter:
                            - lowercase
                    edge_ngram_lowercase:
                        type: custom
                        tokenizer: edge_ngram_tokenizer
                        filter:
                            - lowercase
                normalizer:
                    case_insensitive:
                        type: custom
                        filter:
                            - lowercase
                tokenizer:
                    edge_ngram_tokenizer:
                        type: edge_ngram
                        min_gram: 3
                        max_gram: 15
                        token_chars:
                            - letter
                            - digit
                    alphanum_tokenizer:
                        type: simple_pattern
                        pattern: '[A-Za-z0-9]+'
        mappings:
            properties:
                id:
                    type: long
                metastore_id:
                    type: long
                schema:
                    type: keyword
                    normalizer: case_insensitive
                name:
                    type: keyword
                    normalizer: case_insensitive
                full_name:
                    type: text
                    analyzer: table_name_lowercase
                full_name_ngram:
                    type: text
                    analyzer: edge_ngram_lowercase
                completion_name:
                    type: completion
                    analyzer: keyword
                    contexts:
                        name: metastore_id
                        type: category
                description:
                    type: text
                    analyzer: user_content_analyzer
                created_at:
                    type: long
                columns:
                    type: keyword
                    normalizer: case_insensitive
                golden:
                    type: boolean
                importance_score:
                    type: long
                tags:
                    type: keyword
users:
    index_name: search_users_v1
    type_name: users
    mappings:
        mappings:
            properties:
                id:
                    type: long
                username:
                    type: keyword
                fullname:
                    type: text
                    analyzer: whitespace
                suggest:
                    type: completion
