# Public Configs are shared between backend and frontend and are not sensitive
# --------------- AI Assistant ---------------
ai_assistant:
    enabled: false

    query_title_generation:
        enabled: true

    query_generation:
        enabled: true

    query_auto_fix:
        enabled: true

    table_vector_search:
        enabled: false

survey:
    global_response_cooldown: 2592000 # 30 days
    global_trigger_cooldown: 600 # 10 minutes
    global_trigger_duration: 60 # 1 minute
    global_max_per_week: 6
    global_max_per_day: 3

    surfaces: []

    # Uncomment to enable survey on all surfaces
    # surfaces:
    #     - surface: table_search
    #     - surface: table_view
    #     - surface: text_to_sql
    #     - surface: query_authoring

table_sampling:
    enabled: false
    sample_rates:
        - 0.1
    default_sample_rate: 0 # 0 means no sampling
    sample_user_guide_link: ''
    sampling_tool_tip_delay: 10000 # delay duration (ms) of sampling tool tip
