theme:
    default: default
    tab: general
    options:
        - default
        - dark
        - lush
    helper: Color themes for Querybook.

default_environment:
    default: null
    tab: general
    options: []
    helper: Default environment when going to '/'

default_query_engine:
    per_env: true
    tab: general
    default: '{}'
    options: []
    helper: Default query engine when creating a query cell.

use_previous_query_engine:
    tab: general
    default: enabled
    options:
        - enabled
        - disabled
    helper: Use the previous cell's selected query engine on a DataDoc when available.

datadoc_arrow_key:
    default: enabled
    tab: general
    options:
        - enabled
        - disabled
    helper: Enable the use of arrow keys to navigate through different cells.

notification_preference:
    default: ''
    tab: general
    options: []
    helper: Preference for receiving notifications after query execution.

show_full_view:
    default: disabled
    tab: general
    options:
        - enabled
        - disabled
    helper: Instead of modal, show full view when opening table/execution/snippet

editor_font_size:
    default: medium
    tab: editor
    options:
        - xsmall # Maps to var(--xxsmall-text-size)
        - small # Maps to var(--xsmall-text-size)
        - medium # Maps to var(--small-text-size)
        - large # Maps to var(--text-size)
    helper: Font size of the query editor

result_font_size:
    default: small
    tab: editor
    options:
        - xsmall # Maps to var(--xxsmall-text-size)
        - small # Maps to var(--xsmall-text-size)
        - medium # Maps to var(--small-text-size)
        - large # Maps to var(--text-size)
    helper: Font size of the query result

auto_complete:
    default: all
    tab: editor
    options:
        - all
        - schema
        - none
    helper: Auto complete settings when using editor, all shows both table/column names and key words, schema shows only table/column names

tab:
    default: 'tab space 2'
    tab: editor
    options:
        - 'tab space 2'
        - 'tab space 4'
        - tab
    helper: The spaces setting for code editor, this does not modify the existing code.
